<?php

/**
* Implementation of hook_menu().
*/
function noticias_menu() { 
   
  $items['admin/noticias/nuevo'] = array(
    'title' => 'Nueva',    
    'description' => '',
    'page callback' => 'noticias_nuevo',
    'access arguments' => array('gestionar noticias'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
  ); 

  return $items;
  
}

/**
 *  Function para solapar la vista de node/add/anuncios con la vista de aministracion 
 *
 **/
function noticias_nuevo(){
	
	global $user;
  

	$type = 'noticia';

	$types = node_type_get_types();
	drupal_set_title(t('Create @name', array('@name' => $types[$type]->name)), PASSTHROUGH);


	$node = (object) array(
		'uid' => $user->uid,
		'name' => (isset($user->name) ? $user->name : ''),
		'type' => $type,
		'language' => LANGUAGE_NONE,
	);
	$form_state = array();
	$form_state['build_info']['args'] = array($node);
	form_load_include($form_state, 'inc', 'node', 'node.pages');
	return drupal_build_form($type . '_node_form', $form_state);


}

?>
